# Generated by Django 3.2.7 on 2021-10-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0002_sendemailmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sendemailmodel',
            options={'verbose_name': 'Записи на консультацію', 'verbose_name_plural': 'Записи на консультації'},
        ),
        migrations.AlterField(
            model_name='sendemailmodel',
            name='client_email',
            field=models.EmailField(max_length=70, verbose_name='E-mail'),
        ),
    ]
